import { BaseFormula } from "./BaseFormula";
import { runWfc } from "../wfc/WaveFunctionCollapse";
import { biomePalette, biomeTileset } from "../wfc/tilesets/biome";
import type { FormulaMetadata, FormulaParams, TileGridResult } from "~/types/Formula";

/**
 * Constraint-based generation: a biome map built by Wave Function Collapse over
 * the terrain-ramp tileset. Output is a tile grid, not a scalar field, so this
 * formula implements `createTileGrid` and is rendered by the `tileGrid2d` view.
 */
export class WaveFunctionCollapseFormula extends BaseFormula {
  private cache: { key: string; grid: TileGridResult } | null = null;

  metadata: FormulaMetadata = {
    name: "Wave Function Collapse",
    description: "Biome map generated by tile-adjacency constraint propagation",
    supportedDimensions: ["2d"],
    renderViews: ["tileGrid2d"],
    categories: ["Constraint", "Tiles", "2D"],
    tags: ["wfc", "wave function collapse", "constraint", "biome", "procedural"],
    parameters: {
      gridWidth: {
        name: "grid width",
        description: "Number of tile columns",
        min: 8, max: 64, step: 1, default: 32, isLocked: false
      },
      gridHeight: {
        name: "grid height",
        description: "Number of tile rows",
        min: 8, max: 64, step: 1, default: 32, isLocked: false
      },
      seed: {
        name: "seed",
        description: "Seed for the collapse order and tile choices",
        min: 0, max: 1000, step: 1, default: 7, isLocked: false
      }
    }
  };

  // Not meaningful for a tile grid, but required by the Formula contract.
  calculate(_params: FormulaParams): number {
    return 0;
  }

  createTileGrid(params: FormulaParams): TileGridResult {
    const width = clampInt(params.gridWidth, 8, 64, 32);
    const height = clampInt(params.gridHeight, 8, 64, 32);
    const seed = Math.max(0, Math.floor(params.seed ?? 7));

    const key = `${width}x${height}:${seed}`;
    if (this.cache && this.cache.key === key) return this.cache.grid;

    const { cells } = runWfc(biomeTileset, width, height, seed);
    const grid: TileGridResult = { width, height, cells, palette: biomePalette };

    this.cache = { key, grid };
    return grid;
  }
}

function clampInt(value: number | undefined, min: number, max: number, fallback: number): number {
  if (value == null || !Number.isFinite(value)) return fallback;
  return Math.min(max, Math.max(min, Math.round(value)));
}
